### ISSUE TITLE
Delay in receiving messages

### ISSUE THREAD

**Issue by teehamaral** [jlguardi/yowsup#13]
No error is displayed, however, sometimes the messages arrive instantly the moment the messages take about minutes to being received. I've tried everything, removed the axolotl database to be created again, the number was reauthenticate in whatsapp using yowsup, but the delay persists at certain times, and back to normal (for a while) without having done anything. Someone is going through something that can help me?

**Comment by cfenollosa** [comment]
I'm guessing this is related to #7

**Comment by jlguardi** [comment]
Fixed (I guess) with last commit.
