### ISSUE TITLE
Cannot receive images

### ISSUE THREAD

**Issue by steven-chau** [jlguardi/yowsup#16]
Hi @jlguardi 

Thanks for fixing so many issues for yowsup. I managed to get most of the recent WhatsApp issues fixed by using the main branch of your yowsup repo.

I still have the following issue outstanding though. My application still cannot receive images. It used to work some weeks ago. I would greatly appreciate it if you could get that fixed too. Thanks very much!

**Comment by jlguardi** [comment]
I've just tested an worked for me. 
1. Update my master
1. Reproduce bug and show me how
1. Attach cli logs
1. Report official apps involved

**Comment by freelo** [comment]
Note that you cannot download encrypted images yourself, but you need to use `entity.getMediaContent()` in order to properly decrypt the file contents.

However, this is only a guess, since your error description does not tell anything about the actual issue you have encountered(see above).

**Comment by steven-chau** [comment]
Thank you guys. jlguardi is right in that the cli demo works fine as far as image download is concerned.

It turns out that my issue may be with my WhatsApp account. For some reason, it's unable to receive messages and images. When I run my app with another account, things work again. 

There were no logs. It's just that my `onMessage()` function never gets called with my problematic account.

Anywayz, thank you guys.
