### ISSUE TITLE
[TODO] Fix Encrypted audio/video

### ISSUE THREAD

**Issue by cgraefe** [jlguardi/yowsup#19]
I am currently on jlguardi/master (90999f8) and in spite of what the Wiki claims, I seem to be receiving encrypted audio media messages. These are currently "Unhandled" (yowsup/layers/axolotl/layer.py line 343):

```
DEBUG:yowsup.layers.logger.layer:rx:
<message type="media" notify="XXX" from="XXXXXXXX@s.whatsapp.net" id="..." t="...">
<enc type="pkmsg" mediatype="audio" v="2">
���!������˯�F�Q�t�f�]��J��W4T�!��'Uqʾ�&
...
HEX:3308d2e9c5071221059eede2ebe4c1b1cbaf10c746945106c174d566f75d9e19d64a9896573454d3151a2105acfaaf2755711ccabea226cba38f582ebc328239cddbc46c1f03b043ee6dc84222d403330a2105557178f235aa93f735c6c372bc4a711bfb1d6d021c9e5b6e2f5c25b4adf1e04810ef02180022a00358
...
</enc>
</message>

WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...

WARNING:yowsup.layers.axolotl.layer:Unhandled

```

**Comment by jlguardi** [comment]
Easy to fix but I need to reproduce. Which whatsa.. are you using? Iphone or android? Which version?

**Comment by cgraefe** [comment]
This was sent from an Android phone using WhatsApp version 2.12.556.

I just tried the same on an iPhone using WhatsApp version 2.12.17: Audio messages sent by this client still go unencrypted!

**Comment by cgraefe** [comment]
The same issue applies to video messages btw. Encrypted using current Android client:

```
DEBUG:yowsup.layers.logger.layer:rx:
<message type="media" notify="XXX" from="XXXXXXXX@s.whatsapp.net" id="..." t="...">
<enc type="pkmsg" mediatype="video" v="2">
���!������˯�F�Q�t�f�]��J��W4T�!��'Uqʾ�&ˣ�X.�2�9���l�C�m�B"�3
...
HEX:3308d2e9c5071221059eede2ebe4c1b1cbaf10c746945106c174d566f75d9e19d64a9896573454d3151a2105acfaaf2755711ccabea226cba38f582ebc328239cddbc46c1f03b043ee6dc84222d417330a2105557178f235aa93f735c6c372bc4a711bfb1d6d021c9e5b6e2f5c25b4adf1e04810fb02180022a0170b
...
</enc>
</message>

WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...

WARNING:yowsup.layers.axolotl.layer:Unhandled

```

**Comment by jlguardi** [comment]
Ok, I'll fix soon.

**Comment by cgraefe** [comment]
Awesome. Thank you so much!

**Comment by jlguardi** [comment]
Android 2.12.440 doesn't support audio/video encryption (check with /seq command in cli). So you are using a newer version/token. Is it true?

**Comment by cgraefe** [comment]
Actually no, I'd say. I'm using exactly the commit from your master branch mentioned above without any modifications. Especially none to `yowsup/env/__init__.py` or `yowsup/env/env_android.py`.

I haven't used the cli much, but when I run it in the same virtualenv as my app with the same config the /seq commands yields:

```
...
<prop name="e2e_audio" value="0">
</prop>
<prop name="e2e_blists" value="1">
</prop>
<prop name="e2e_groups" value="1">
</prop>
<prop name="e2e_images" value="1">
</prop>
<prop name="e2e_video" value="0">
</prop>
<prop name="e2e_voip" value="1">
...
```

Is that what you are referring to?

**Comment by jlguardi** [comment]
Yes, e2e_audio,video =0

De: cgraefe
Enviado: miércoles, 30 de marzo de 2016 17:58
Para: jlguardi/yowsup
Responder a: jlguardi/yowsup
CC: jlguardi
Asunto: Re: [jlguardi/yowsup] [TODO] Fix Encrypted audio/video (#19)

Actually no, I'd say. I'm using exactly the commit from your master branch mentioned above without any modifications. Especially none to `yowsup/env/__init__.py` or `yowsup/env/env_android.py`.

I haven't used the cli much, but when I run it in the same virtualenv as my app with the same config the /seq commands yields:

```
...
<prop name="e2e_audio" value="0">
</prop>
<prop name="e2e_blists" value="1">
</prop>
<prop name="e2e_groups" value="1">
</prop>
<prop name="e2e_images" value="1">
</prop>
<prop name="e2e_video" value="0">
</prop>
<prop name="e2e_voip" value="1">
...
```

Is that what you are referring to?

---

**Comment by cgraefe** [comment]
I am still receiving those encrypted messages with this exact setup though. I will be AFK soon; if you require more info I'll be happy to supply it tomorrow.

**Comment by salmos23** [comment]
To Jlguardi 

Hello , I 'm trying to download images and the download is encrypted. Is there any way to download without encryption ? Thank you.

2016-03-30 16:18:02,104 [wa] INFO - Received image /home/ariel2510/www/productos/tmp80jkE2.jpg 
2016-03-30 16:18:02,105 [wa] DEBUG - 
2016-03-30 16:18:02,105 [walistener.wa_layer] DEBUG - [Media Type:image, Size:14418, URL:https://mmi666.whatsapp.net/d/uKDDl78O7Zmi3n2PJYQQU1b8XqU/AlK0PFHVbbQ1b6AH8QuVvqSSSnomRLXVJv43XRLv60v1.enc]

**Comment by jlguardi** [comment]
@salmos23 this isn't a log of updated cli of my master. 
Now, I print a local path where media is stored.

**Comment by salmos23** [comment]
@jlguardi Are you downloading succesful no encrypted? Thanks for your help.

**Comment by jlguardi** [comment]
Yes, update to master and open file reported by cli.
However, this thread is for video/audio not for images. If required, open an issue please.

**Comment by salmos23** [comment]
I opened for Encrypted Images Issue #24 (Encrypted Images. #24)

**Comment by jlguardi** [comment]
Fixed (just available in S40 env)
