### ISSUE TITLE
Unable to send and receive message after logged in

### ISSUE THREAD

**Issue by harpreetrekhi** [jlguardi/yowsup#20]
Hi,

When connected to whatsapp CLI, even it shows message has been sent but it is not received to end subscriber.

Also when I am sending whatsapp message to yowsup number then it displays below error, even though on it says message delivered but not read by yowsup (no blue tick mark)

pi@jigsaw:~/yowsup $
pi@jigsaw:~/yowsup $ yowsup-cli demos --yowsup --config config
# Yowsup Cli client

Type /help for available commands

Auth: Logged in!
[connected]:/message send 9xxxxxxxx "Hi there"
[connected]:Sent: 1459348129-1
[connected]:

[connected]:
[connected]:
[connected]:WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 0
WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 0
WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 0
WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 0
WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 0
WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 0
WARNING:yowsup.layers.axolotl.layer:Too many retries!! Going to send the delivery receipt myself!

[connected]:

**Comment by jlguardi** [comment]
Post debug logs (-d flag). And be sure that last master is running where some issues with acks were fixed.

**Comment by harpreetrekhi** [comment]
OK, resolved this by removing 

/home/.yowsup/<phone number1>/axolotl.db
/home/.yowsup/<phone number2>/axolotl.db

Now everything works like charm.. thanks
