### ISSUE TITLE
Android App Crush when using yowsup in a group

### ISSUE THREAD

**Issue by anativ** [jlguardi/yowsup#26]
Steps
1. Run echo app
2. create a new group via android app and add yowsup
3. Android WhatsApp app crush as long as yowsup is running

Any idea?

**Comment by jlguardi** [comment]
Add logs of cli (-d flag)

**Comment by anativ** [comment]
here are the logs
https://gist.github.com/anativ/90a4feb74223f4f85a10a6b3c2c00bd0

I guess the logs won't help much right now cause the apps keep crushes even after I closed yowsup
when my app will be up again I will post debug logs of the full scenario

I will update soon

**Comment by jlguardi** [comment]
This isn't the last code of jlguardi/yowsup/master.
Update it.

De: anativ
Enviado: jueves, 31 de marzo de 2016 09:22
Para: jlguardi/yowsup
Responder a: jlguardi/yowsup
CC: jlguardi
Asunto: Re: [jlguardi/yowsup] Android App Crush when using yowsup in a group (#26)

here are the logs
https://gist.github.com/anativ/e60e216619a4d0a0a927b791262eee20

I guess the logs won't help much right now cause the apps keep crushes even after I closed yowsup
when my app will be up again I will post debug logs of the full scenario

I will update soon

---

**Comment by anativ** [comment]
Sorry,
Works with the latest code!
