### ISSUE TITLE
When installing got "ImportError: No module named axolotladdress"

### ISSUE THREAD

**Issue by shedokan** [jlguardi/yowsup#27]
I just tried moving to this repository from tgalal/yowsup but got an "ImportError"

All I did is:
`pip uninstall yowsup2`

and:
`sudo pip install sudo pip install git+https://github.com/jlguardi/yowsup.git@master`

Here's the error log:

> Mar 31 07:07:09 python[18204]: File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/interface/interface.py", line 7, in <module>
> Mar 31 07:07:09 python[18204]: from yowsup.layers.axolotl.layer import YowAxolotlLayer
> Mar 31 07:07:09 python[18204]: File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/**init**.py", line 1, in <module>
> Mar 31 07:07:09 python[18204]: from .layer import YowAxolotlLayer
> Mar 31 07:07:09 python[18204]: File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 27, in <module>
> Mar 31 07:07:09 python[18204]: from axolotl.axolotladdress import AxolotlAddress
> Mar 31 07:07:09 python[18204]: ImportError: No module named axolotladdress

Did I do something wrong?
Thank you

**Comment by jlguardi** [comment]
Read closed issues
