### ISSUE TITLE
Home automation using yowsup

### ISSUE THREAD

**Issue by harpreetrekhi** [jlguardi/yowsup#31]
Hi 

Anyone having working python script to send and receive whatsapp messages using python?

I tried multiple scripts online but I guess due to some code changes in yowsup, those scripts are not working anymore.

Any tested run.py and layer.py will be helpful along with description of how to use the scripts.

Thanks in advance. Consider me as a noob :)

**Comment by jlguardi** [comment]
@harpreetrekhi use yowsup-cli demos -c config.cfg -s dest text
Or use interactiv mode with -y instead of -s.

**Comment by harpreetrekhi** [comment]
@jlguardi yes that is the simplest usage of yowsup, even the help message of yowsup explains that but this does not solves my purpose..

I want to take some actions based on the keywords received from particular subscribers and send back the output to the same number, I am looking for a compiled, working code for this solution.

Can you help in this regard.?
