### ISSUE TITLE
Login Failed, reason not-authorized

### ISSUE THREAD

**Issue by chenwayne** [jlguardi/yowsup#34]
Hi @jlguardi ,

I am a noob on this wonderful whatsapp lib. Currently I met this problem: 'Login failed, reason not-authorize'. I have read through a lot threads in tgalal's git repo. It guides me here, using your latest code on master branch. But I still have this error either for old and newly registered whatsapp numbers. I think there are still a lot like me, who are confused how to use your master repo correctly to overcome this login failed issue. 

Best regards!
Wayne

**Comment by jlguardi** [comment]
Now tgalal master is working again (most of the functionality). Update with pip and use it. To use mine, download from master and do setup.py (Remember to get axolotl from develop -> see closed issues)
