### ISSUE TITLE
Image Format receive

### ISSUE THREAD

**Issue by rafaelpstein** [jlguardi/yowsup#41]
Hi guys,

Now system receive image with extension .enc and i cant´t see. If i change .enc to .jpg for example  o can´t see too.
Example:
Echoing image https://mmi294.whatsapp.net/d/KfHpZxaXKUCBQwtHRe4nFVcAaP8/Ai0U67VmG1n9IEkOTtWBnIRdJOlbMb1IlFLmK5yDzbu1.enc to XXXXXXX

**Comment by jlguardi** [comment]
To get unencrypted data use mediaMessage.getMediaContent(). In cli you have an example to write image to disk.

**Comment by rafaelpstein** [comment]
work fine!!   thanks
