### ISSUE TITLE
'ValueError: Unhandled' on group participant removal

### ISSUE THREAD

**Issue by uraid** [jlguardi/yowsup#60]
When a group participant is removed, yowsup has problems reading the next text message to that group and raises a ValueError exception:
[valueError.txt](https://github.com/jlguardi/yowsup/files/211151/valueError.txt)

When restarting yowsup client after this exception, a new exception is thrown once (the next restart fixes and ignores that first text message after the removal):
[TypeError.txt](https://github.com/jlguardi/yowsup/files/211155/TypeError.txt)

**Comment by jlguardi** [comment]
First issue fixed in  6f7d0c6 (tgalal wa16 didn't have the error)
Second issue related with #62 and #64.
Close this issue to and keep the other two issues
