### ISSUE TITLE
[BUG] mime.types resource raises an exception on long path in Windows

### ISSUE THREAD

**Issue by Miguel1422** [jlguardi/yowsup#66]
Hi
It seems to be a problem to start the the demos on Windows, I tried on Linux and it worked but on windows doesn't, here is the error. And sorry for my bad english :(

> PS C:\WhatsAppB> python yowsup-cli demos --yowsup --config config.txt
> Traceback (most recent call last):
>   File "yowsup-cli", line 324, in <module>
>     if not parser.process():
>   File "yowsup-cli", line 228, in process
>     self.startCmdline()
>   File "yowsup-cli", line 250, in startCmdline
>     from yowsup.demos import cli
>   File "C:\WhatsAppB\yowsup\demos\cli__init__.py", line 1, in <module>
>     from .stack import YowsupCliStack
>   File "C:\WhatsAppB\yowsup\demos\cli\stack.py", line 1, in <module>
>     from yowsup.stacks import  YowStackBuilder
>   File "C:\WhatsAppB\yowsup\stacks__init__.py", line 1, in <module>
>     from .yowstack import YowStack, YowStackBuilder
>   File "C:\WhatsAppB\yowsup\stacks\yowstack.py", line 4, in <module>
>     from yowsup.layers.auth                        import YowCryptLayer, YowAuthenticationProtocolLayer
>   File "C:\WhatsAppB\yowsup\layers\auth__init__.py", line 2, in <module>
>     from .layer_authentication import YowAuthenticationProtocolLayer
>   File "C:\WhatsAppB\yowsup\layers\auth\layer_authentication.py", line 4, in <module>
>     from yowsup.common.tools import TimeTools
>   File "C:\WhatsAppB\yowsup\common\tools.py", line 182, in <module>
>     class MimeTools:
>   File "C:\WhatsAppB\yowsup\common\tools.py", line 185, in MimeTools
>     mimetypes.init([MIME_FILE]) # Append whatsapp mime.types
>   File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\mimetypes.py", line 352, in init
>     if os.path.isfile(file):
>   File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\genericpath.py", line 30, in isfile
>     st = os.stat(path)
> **ValueError: stat: path too long for Windows**

**Comment by freelo** [comment]
Is your python installed into AppData? Try something like C:\Python35. Then there is less chance of paths getting too long.
