### ISSUE TITLE
No such file or directory ... mime.types

### ISSUE THREAD

**Issue by chriso0710** [jlguardi/yowsup#70]
Hi @jlguardi, thanks for your fantastic work in this project!

I was just testing your latest branches (master and mime_types_in_egg). 
I uninstalled old tgagal/yowsup with pip.
I installed your fork via pip directly from your github repos. But I keep getting an error from missing mime.types file. Same error in master and mime_types_in_egg branches.

```
IOError: [Errno 2] No such file or directory: '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yowsup/common/mime.types'
```

After uninstalling with pip I see the following file which gets removed:

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/yowsup/common/mime.types
```

I seem to have fixed the error by creating a symlink from
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/yowsup/common/mime.types
to
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yowsup/common/mime.types

Any idea whats going on?  

Christian

**Comment by jlguardi** [comment]
I'm not a python developer. So, I'm sure that packaging could be wrong.

However, I've tested and It worked with:

```
sudo setup.py install
```

But, mime.types is not present if:

```
python setup.py bdist
pip install dist/yowsup2-2.4.48.linux-i686.tar.gz
```

Could someone with python packaging expertice check this error?

**Comment by chriso0710** [comment]
Additional info: I'm installing directly from github with

```
 sudo pip install git+https://github.com/jlguardi/yowsup.git
```

**Comment by kimenye** [comment]
Python packaging is a bit tricky, but I think we need a MANIFEST.in file with the line below to work as intended.

```
include yowsup/common/mime.types
```
