### ISSUE TITLE
Unblock number for wa

### ISSUE THREAD

**Issue by thundergreen** [jlguardi/yowsup#76]
Got an success in reactivation of my number ! Just send an email to the support and ask them what's going wrong there .I had to send screenshots of proper wa install and they will unblock my number

**Comment by chriso0710** [comment]
That really works??
What kind of screenshots did you send them? Did you have to use your blocked number in Whatsapp on a real phone?

**Comment by thundergreen** [comment]
Well till now no response of wa .i send Screenshot to show them that I use the original Messenger .still waiting for unblocking.

**Comment by thundergreen** [comment]
Number has been unblocked
