### ISSUE TITLE
Receive incomplete WhatsApps (not always)

### ISSUE THREAD

**Issue by MauricioAHM** [jlguardi/yowsup#77]
Hi, I was wondering that someone knows how to solve this, or where can I find information about it.
I annex a picture where i have the problem. 
I'm running the command 

sudo yowsup-cli demos --yowsup --config config

![captura de pantalla 49](https://cloud.githubusercontent.com/assets/18564255/14660996/d7b93d56-066f-11e6-9d40-2740549fcd41.png)

**Comment by jlguardi** [comment]
@MauricioAHM Are you using my code or tgalal code?
I've just checked out my mster and it woks ok about padding.
Please, post logs from

```
yowsup-cli demos -y -d -c configfile
```

By now, I'll close this issue but don't hesitate to re-open it.

**Comment by MauricioAHM** [comment]
First of all thank you.

Hi, I'm using tagalal code, I made the corections of https://github.com/tagalal/yowsup/pull/1390/comité/956626e77fc4aa777da65f57978a27b0518a8410
But the problem persiste.

Best regards.

Enviado desde mi Sony Xperia™ smartphone de Telcel

---- jlguardi escribió ----

@MauricioAHMhttps://github.com/MauricioAHM Are you using my code or tgalal code?
I've just checked out my mster and it woks ok about padding.
Please, post logs from

yowsup-cli demos -y -d -c configfile

By now, I'll close this issue but don't hesitate to re-open it.

**Comment by MauricioAHM** [comment]
Hi @jlguardi these are the logs after running the code and sending a string "Hola".

Thanks in advance for your support!

`yowsup-cli demos -y -d -c configfile`

```
[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="mauricio ahh" from="5214521155667@s.whatsapp.net" id="44EEF5E7F963B0401D2E5C178A1429" t="1461888336">
<enc type="msg" v="2">
3
!V▒▒|▒▒▒▒y▒▒$▒▒▒▒▒$▒▒▒▒▒:▒rM."P%NѠTpݤG.▒(K▒▒▒|/▒5▒▒▒▒▒
▒~▒5Ya*▒v▒▒▒n"▒▒uYm▒i▒Q5▒mͯw▒▒g▒▒D▒
                                  ▒DY▒*]#▒鹃3M▒
HEX:330a210556a0ea7cbfcfe0c379b3048824efc6d5e4e0249cbc8f9e1cf591973abb724d2e100518002250254ed1a05470dda4472ef0284b0ed3c8008b107c2ff53598b8908f13c21f1e0ac47ee63559612aa17684158ace6e0022a09475596dc869ff5135af136dcdaf77b58967ace644950b16e7a34459b62a5d23c8e9b983334dc0
</enc>
</message>

ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="5214521155667@s.whatsapp.net" type="retry" id="44EEF5E7F963B0401D2E5C178A1429">
<retry count="1" v="2" t="1461888336" id="44EEF5E7F963B0401D2E5C178A1429">
</retry>
<registration>
x▒G
HEX:78148547
</registration>
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="5214521155667@s.whatsapp.net" class="receipt" id="44EEF5E7F963B0401D2E5C178A1429">
</ack>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="1">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="5214432178340@s.whatsapp.net" id="1" t="1461888362">
</iq>

Iq:
ID: 1
Type: result
from: 5214432178340@s.whatsapp.net


```

**Comment by jlguardi** [comment]
You have deleted axolotl.db and/or started in other computers. Send a message to recipient and try again.
