### ISSUE TITLE
echoclient not working?

### ISSUE THREAD

**Issue by harpreetrekhi** [jlguardi/yowsup#80]
Hi,

echoclient is not working, below are the debug logs,

I sent some messages they are not even delivered & also not echo'd back, any issues?

pi@jigsaw:~/yowsup $ yowsup-cli demos -d -e -c config
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e2.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="917053017198" mechanism="WAUTH-2">
▒q      ▒▒▒*▒▒ٮ▒M▒`▒
埞▒8▒▒/,1Gf▒r▒▒0▒▒I▒▒>50▒Qv     ▒▒▒!f4▒?ޠ~q-▒Qv~▒▒Ԝν▒
HEX:947109b21abbb22aa6d0d9aedc4dbe60ca0ae59f9ede3890fd2f2c31471466fa1172bfec30bcce49961e883e353019b6517609effeff142166349e3fdea07e0e712db951767e86fdd49ccebdbe1a
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1456506351" expiration="4444444444" props="5" t="1461346016">
▒L[▒▒▒▒▒p▒Բ+$▒A}▒
HEX:bb4c5bd2f2c508b4ad9d70bbd4b22b24ea417dae
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1461346016" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt offline="3" from="919818801098@s.whatsapp.net" id="1461145822A15" t="1461145824">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" id="1461145822A15" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt type="read" offline="3" from="919818801098@s.whatsapp.net" id="1461145822A15" t="1461145824">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" type="read" id="1461145822A15" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt type="read" offline="3" from="919818801098@s.whatsapp.net" id="1461145825A18" t="1461145826">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" type="read" id="1461145825A18" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt offline="3" from="919818801098@s.whatsapp.net" id="1461145825A18" t="1461145826">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" id="1461145825A18" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt type="read" offline="3" from="919818801098@s.whatsapp.net" id="1461145825A18" t="1461145826">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" type="read" id="1461145825A18" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt type="read" offline="3" from="919818801098@s.whatsapp.net" id="1461145833A21" t="1461145834">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" type="read" id="1461145833A21" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt offline="2" from="919818801098@s.whatsapp.net" id="1461145833A21" t="1461145834">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" id="1461145833A21" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt type="read" offline="2" from="919818801098@s.whatsapp.net" id="1461145833A21" t="1461145834">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" type="read" id="1461145833A21" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt type="read" offline="2" from="919818801098@s.whatsapp.net" id="1461145838A24" t="1461145839">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" type="read" id="1461145838A24" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt offline="2" from="919818801098@s.whatsapp.net" id="1461145838A24" t="1461145839">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="919818801098@s.whatsapp.net" id="1461145838A24" class="receipt">
</ack>

**Comment by jlguardi** [comment]
You aren't using my latest master (I guess). This issue should be fixed 2 weeks ago. 
Update your code, check the installation and try again. If persists, reopen please.
