### ISSUE TITLE
Group jid structure changed?

### ISSUE THREAD

**Issue by spsneo** [jlguardi/yowsup#9]
I am seeing that group jid's format is numberAnumber instead of number-number
Is anybody else also seeing this pattern?

**Comment by spsneo** [comment]
After further investigation it seems group jid that we are getting from server is numberAnumber 
But when we query group info or when we send messages to group, group jid should be in the format number-number

**Comment by jlguardi** [comment]
Please post logs and say what version of yowsup and official app are you using for testing.

**Comment by spsneo** [comment]
I am using your master branch latest commit for yowsup client.

**Comment by spsneo** [comment]
```
DEBUG:yowsup.layers.logger.layer:rx:
<ack type="read" participant="919812307297@s.whatsapp.net" from="918894788585A1425100178@g.us" class="receipt" id="449C7988E4CBA9B40CB">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="read" participant="919812307297@s.whatsapp.net" from="918894788585A1425100178@g.us" class="receipt" id="449C7988E4CBA9B40CC">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="read" participant="919812307297@s.whatsapp.net" from="918894788585A1425100178@g.us" class="receipt" id="449C7988E4CBA9B40CD">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="read" participant="919812307297@s.whatsapp.net" from="918894788585A1425100178@g.us" class="receipt" id="449C7988E4CBA9B40CE">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="read" participant="919812307297@s.whatsapp.net" from="918894788585A1425100178@g.us" class="receipt" id="449C7988E4CBA9B40CF">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="read" participant="919812307297@s.whatsapp.net" from="918894788585A1425100178@g.us" class="receipt" id="449C7988E4CBA9B40C10">
</ack>
```

**Comment by spsneo** [comment]
If you notice from attribute in the above log you would see that group jid is `<number>A<number>`

**Comment by jlguardi** [comment]
Which SO and whatsa.. version has 918xxxx585?

**Comment by spsneo** [comment]
I am not sure. I don't own that number. These are offline messages. I am not receiving new messages. I just realized that I am receiving same messages every time I connect. Is it because I am sending read receipt to wrong group jid?

**Comment by jlguardi** [comment]
It was was bug. Reverted d429c16.
