### ISSUE TITLE
Connection Closed. for android env. media cannot decrypt for s40

### ISSUE THREAD

**Issue by chenwayne** [jlguardi/yowsup#95]
I encountered following problem:
When using android(_VERSION = "2.16.254"), the connection to whatsapp keep drop, error message is: Disconnected: Connection Closed
When using S40, connection is ok, but cannot decrypt media content. 
Any example for how to get decrypted media content?

**Comment by jlguardi** [comment]
@chenwayne see pull requests or just use my master where media decrypt is fixed.
